stages:
  - build
  - test

jobs:
  include:
    - stage: build
      script:
        - mkdir build
        - cd build
        - cmake ../
        - cmake --build .

    - stage: test
      script:
        - echo "hello world!"
